### ISSUE TITLE
Example fails when debug print removed

### ISSUE THREAD

**Issue by ghost** [dvarrel/DHT22#1]
When I run your example as is, the temp and humidity readings are correct. However, if I comment out the line that calls and prints the dht22.debug(), the subsequent temp and humidity readings all fail.

**Comment by tinkering4fun** [comment]
Hi, 
I encountered the same issue,  and fixed it already in my fork :-)  ===> branch esp32
Root cause is a missing call to measureTimings()  when debug() method is not called, thus readSensor() misses the values and fails ...
By fixing and playing with this, I felt a need to apply some enhancements e.g a dht22.begin().
Provided some new examples where I try to explain my ideas ...

btw: I run this code on a ESP32 with AM2305 sensor [link](https://www.exp-tech.de/sensoren/temperatur/7929/am2305-humidity-temperature-sensor) which seems to be compatible with DHT22.

Regards
Werner

**Comment by dvarrel** [comment]
new code not working with arduino uno .
release 1.0.2 is ok


seems am2305 is different than am2302;.;.
am2302 have resistor pullup and am2305 not...

**Comment by dvarrel** [comment]
seems am2305 is different than am2302;.;.

**Comment by dvarrel** [comment]
i made a new branch dev for your code

**Comment by dvarrel** [comment]
> When I run your example as is, the temp and humidity readings are correct. However, if I comment out the line that calls and prints the dht22.debug(), the subsequent temp and humidity readings all fail.

it's because the defaults values for timing have not been indicate in the source dht22.h
1.0.5 solve the problem

**Comment by tinkering4fun** [comment]
Sorry for any inconvenience, did  not get the message ...
Is there anything I can / should do on this? 

Unfortunately my AM2305 is already productive and mounted outside so I cannot play with it.
But I could buy an AM2302 for testing on Uno (AM2305 is too expensive for just  experimenting).
As far as I remember, I added a pullup resistor to the CPU signal pin.
As said, I used ESP32 in my project. ESP32 is way faster than Uno, so my code may fail because it's too resource hungry?
To be honest, I even run the sensor code in a own thread in 2nd core, to avoid blocking of my main  application code during the OneWire data transfers.
My project was a Modbus RTU server which monitors BME280 and AM2305 sensor.

**Comment by ghost** [comment]
I see that Version 1.0.5 is available in the Arduino IDE, and I have updated it. I'm not near my particular ESP32 that had the original problem to test it. Will be in a few weeks. Thanks for the solution...

**Comment by dvarrel** [comment]
> Sorry for any inconvenience, did not get the message ... Is there anything I can / should do on this?
> 
> Unfortunately my AM2305 is already productive and mounted outside so I cannot play with it. But I could buy an AM2302 for testing on Uno (AM2305 is too expensive for just experimenting). As far as I remember, I added a pullup resistor to the CPU signal pin. As said, I used ESP32 in my project. ESP32 is way faster than Uno, so my code may fail because it's too resource hungry? To be honest, I even run the sensor code in a own thread in 2nd core, to avoid blocking of my main application code during the OneWire data transfers. My project was a Modbus RTU server which monitors BME280 and AM2305 sensor.

perhaps am2305 is very different ( more accurate ?)  than am2302 ( you have to wait ~1s to stabilize Voltage on powerOn ), it may be better to make another librarie ?
